server:
  port: '8080'
security:
  api:
    key: ${APIKEY}
spring:
  docker:
    compose:
      enabled: 'true'
      file: src/infra/docker-compose.yml
selenium:
  driver-path: "http://seleniarm:4444"