name: Build and Push to ACR

on:
  push:
    branches:
      - 'master'
      - 'SW-78--CI/CD-workflow'
      - 'releases/**'
      - 'release/**'

env:
  IMAGE_NAME: 'pdf_generator'
  VERSION: 'v1.0.0'

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Print
        run: echo "You are in Build phase"

        #TODO: push image to the Azure Container Registry

  deploy-dev:
    name: Dev Deployment
    needs: build
    uses: ./.github/workflows/publish.yml
    with:
      environmentName: "Development"
      branchName: ${{ github.ref }}

  deploy-stage:
    name: Stage Deployment
    needs: deploy-dev
    uses: ./.github/workflows/publish.yml
    with:
      environmentName: "Staging"
      branchName: ${{ github.ref }}

  deploy-prod:
    name: Prod Deployment
    needs: deploy-stage
    uses: ./.github/workflows/publish.yml
    with:
      environmentName: "Production"
      branchName: ${{ github.ref }}
