name: Build and Push to ACR

on:
  push:
    branches:
      - 'master'
      - 'SW-78--CI/CD-workflow'
      - 'releases/**'
      - 'release/**'

env:
  IMAGE_NAME: 'pdf_generator'
  VERSION: 'v1.0.0'

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          server-id: github

      - name: Build JAR with Maven
        env:
          APIKEY: ${{ secrets.API_KEY }}
        run: mvn clean package

      - name: Build image with docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/infra/Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

        #TODO: push image to the Azure Container Registry

  deploy-dev:
    name: Dev Deployment
    needs: build
    uses: ./.github/workflows/publish.yml
    with:
      environmentName: "Development"
      branchName: ${{ github.ref }}

  deploy-stage:
    name: Stage Deployment
    needs: deploy-dev
    uses: ./.github/workflows/publish.yml
    with:
      environmentName: "Staging"
      branchName: ${{ github.ref }}

  deploy-prod:
    name: Prod Deployment
    needs: deploy-stage
    uses: ./.github/workflows/publish.yml
    with:
      environmentName: "Production"
      branchName: ${{ github.ref }}
