name:  Create Docker Image

env:
  JAVA_VERSION: '21' 
  IMAGE_NAME: 'pdf_generator'
  VERSION: 'v1.0.0'

on: [push]

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          server-id: github

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Build image with docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: verify image creation
        run: docker images
