name:  A job to create Docker Image

env:
  JAVA_VERSION: '21' 
  IMAGE_NAME: 'Pdf_Generator'
  VERSION: 'v1.0.0'

on: [push]

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "The job is triggered by the branch ${{ github.ref }} and initiated by ${{ github.actor }}"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'oracle'
          cache: 'maven'
          server-id: github

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Build image with docker
        run: |
          cd src/infra
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} -f .
          docker images
