name: Publish to Azure

on:
  workflow_call:
    inputs:
      environmentName:
        description: The environment to deploy to
        required: true
        type: string
      branchName:
        type: string
        description: The branch on which the workflow was triggered
        required: true

jobs:
  deploy:
    name: Deploy to the ${{ inputs.environmentName }} Environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environmentName }}
    if: |
      ( 
      ${{ inputs.branchName }} == 'refs/heads/SW-78--CI/CD-workflow' &&
      ${{ inputs.environment }} == 'Development') ||
      (${{ inputs.branchName }} == 'refs/heads/release' &&
      (${{ inputs.environment }} == 'Staging' ||
      ${{ inputs.environment }} == 'Production')
      )
    steps:
      - name: Print the envName and branch name
        run: echo "${{ inputs.environmentName }} ${{ inputs.branchName }}"

        #TODO: pull image from the registry and run pulumi scripts to deploy on sepcified env
